//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANVAS
    {
        public string CANVASE_SIZE { get; set; }
        public string MATERIAL { get; set; }
        public decimal PRODUCT_ID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
