//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRAYON
    {
        public string CRAYON_TYPE { get; set; }
        public string SHAPE { get; set; }
        public decimal PRODUCT_ID { get; set; }
        public Nullable<decimal> COLOUR_ID { get; set; }
    
        public virtual COLOUR COLOUR { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
