//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERORDER
    {
        public decimal NUMBER_OF_PRODUCTS { get; set; }
        public Nullable<decimal> ORDER_ID { get; set; }
        public Nullable<decimal> PRODUCT_ID { get; set; }
    
        public virtual INFOORDERCUSTOMER INFOORDERCUSTOMER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
