//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.INFOORDERCUSTOMERs = new HashSet<INFOORDERCUSTOMER>();
        }
    
        public decimal CUSTOMER_ID { get; set; }
        public string NAME { get; set; }
        public string BANK_ACCOUNT { get; set; }
        public string EMAIL { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string POST_CODE { get; set; }
        public string CITY { get; set; }
        public string STREET_NAME { get; set; }
        public string HOUSE_NUMBER { get; set; }
        public string LOCAL_NUMBER { get; set; }
        public Nullable<decimal> DISCOUNT_POINTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFOORDERCUSTOMER> INFOORDERCUSTOMERs { get; set; }
    }
}
