//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNTPOINT
    {
        public decimal DISCOUNT { get; set; }
        public decimal POINTS_MINIMUM { get; set; }
        public decimal POINTS_MAXIMUM { get; set; }
    }
}
