//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<BRUSH> BRUSHES { get; set; }
        public virtual DbSet<CANVAS> CANVASES { get; set; }
        public virtual DbSet<COLOUR> COLOURS { get; set; }
        public virtual DbSet<CRAYON> CRAYONS { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public virtual DbSet<DELIVERER> DELIVERERS { get; set; }
        public virtual DbSet<INFOORDERCUSTOMER> INFOORDERCUSTOMERs { get; set; }
        public virtual DbSet<INFOSTOREORDER> INFOSTOREORDERs { get; set; }
        public virtual DbSet<INK> INKS { get; set; }
        public virtual DbSet<MARKER> MARKERS { get; set; }
        public virtual DbSet<NOTEBOOK> NOTEBOOKS { get; set; }
        public virtual DbSet<PAINT> PAINTS { get; set; }
        public virtual DbSet<PAPERPAD> PAPERPADS { get; set; }
        public virtual DbSet<PENCIL> PENCILS { get; set; }
        public virtual DbSet<PEN> PENS { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<SCULPTINGMATERIAL> SCULPTINGMATERIALS { get; set; }
        public virtual DbSet<SET> SETS { get; set; }
        public virtual DbSet<CUSTOMERORDER> CUSTOMERORDERS { get; set; }
        public virtual DbSet<DISCOUNTPOINT> DISCOUNTPOINTS { get; set; }
        public virtual DbSet<STOREORDER> STOREORDERS { get; set; }
    }
}
