//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAPERPAD
    {
        public Nullable<decimal> PAGES_NUMBER { get; set; }
        public string PAPER_PAD_SIZE { get; set; }
        public Nullable<decimal> GRAMMAGE { get; set; }
        public decimal PRODUCT_ID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
